export interface Lead {
  id: string;
  name: string;
  contact: string;
  altPhone: string;
  email: string;
  status: string;
  qualification: string;
  interest: string;
  source: string;
  assignedTo: string;
  createdAt: string;
  jobInterest: string;
  state: string;
  city: string;
  passoutYear: string;
  heardFrom: string;
}
export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Karl Legros',
    contact: '857.256.0540',
    altPhone: '617-555-0189',
    email: 'klegros@email.com',
    status: 'follow-up',
    qualification: 'Masters',
    interest: 'Mobile Development',
    source: 'Email Campaign',
    assignedTo: 'John Doe',
    createdAt: '2025-05-22',
    jobInterest: 'iOS Development',
    state: 'CA',
    city: 'Los Angeles',
    passoutYear: '2022',
    heardFrom: 'Webinar'
  },
  {
    id: '2',
    name: 'Bridget Hayes',
    contact: '1-318-365-0874 x98876',
    altPhone: '504-555-0122',
    email: 'bhayes@techcorp.com',
    status: 'qualified',
    qualification: 'PhD',
    interest: 'Digital Marketing',
    source: 'Website',
    assignedTo: 'John Doe',
    createdAt: '2025-05-21',
    jobInterest: 'SEO Strategy',
    state: 'LA',
    city: 'New Orleans',
    passoutYear: '2020',
    heardFrom: 'Blog'
  },
  {
    id: '3',
    name: 'Dr. Lawrence Cummings IV',
    contact: '314.612.3224 x796',
    altPhone: '417-555-0198',
    email: 'lcummings@medschool.edu',
    status: 'qualified',
    qualification: 'High School',
    interest: 'Mobile Development',
    source: 'Cold Call',
    assignedTo: 'Jane Smith',
    createdAt: '2025-05-20',
    jobInterest: 'Android Development',
    state: 'MO',
    city: 'Kansas City',
    passoutYear: '2023',
    heardFrom: 'Referral'
  },
  {
    id: '4',
    name: 'Amos D\'Amova',
    contact: '275-600-3449 x992',
    altPhone: '212-555-0155',
    email: 'adamo@datascience.io',
    status: 'converted',
    qualification: 'Bachelors',
    interest: 'Data Science',
    source: 'Social Media',
    assignedTo: 'Jane Smith',
    createdAt: '2025-05-19',
    jobInterest: 'Machine Learning',
    state: 'NY',
    city: 'Buffalo',
    passoutYear: '2021',
    heardFrom: 'LinkedIn'
  },
  {
    id: '5',
    name: 'Miss Norma Predovic',
    contact: '(866) 273-8839 x5756',
    altPhone: '305-555-0173',
    email: 'npredovic@analytics.com',
    status: 'converted',
    qualification: 'High School',
    interest: 'Data Science',
    source: 'Website',
    assignedTo: 'Emily Davis',
    createdAt: '2025-05-19',
    jobInterest: 'Data Visualization',
    state: 'FL',
    city: 'Miami',
    passoutYear: '2019',
    heardFrom: 'Google Ads'
  },
  {
    id: '6',
    name: 'Raul Kub',
    contact: '1-982-565-4955 x7464',
    altPhone: '512-555-0166',
    email: 'raulk@webdev.net',
    status: 'qualified',
    qualification: 'Other',
    interest: 'Web Development',
    source: 'Social Media',
    assignedTo: 'Jane Smith',
    createdAt: '2025-05-18',
    jobInterest: 'Full Stack Development',
    state: 'TX',
    city: 'Houston',
    passoutYear: '2022',
    heardFrom: 'Twitter'
  },
  {
    id: '7',
    name: 'Rickey Swift',
    contact: '(389) 546-9831 x1408',
    altPhone: '404-555-0133',
    email: 'rswift@mobileapps.com',
    status: 'new',
    qualification: 'Masters',
    interest: 'Mobile Development',
    source: 'Social Media',
    assignedTo: 'Robert Johnson',
    createdAt: '2025-05-18',
    jobInterest: 'Flutter Development',
    state: 'GA',
    city: 'Atlanta',
    passoutYear: '2024',
    heardFrom: 'Facebook'
  },
  {
    id: '8',
    name: 'Ernestine Leamon',
    contact: '(744) 349-5353 x5778',
    altPhone: '602-555-0144',
    email: 'eleamon@webdesign.co',
    status: 'new',
    qualification: 'High School',
    interest: 'Web Development',
    source: 'Website',
    assignedTo: 'Emily Davis',
    createdAt: '2025-05-17',
    jobInterest: 'Frontend Development',
    state: 'AZ',
    city: 'Phoenix',
    passoutYear: '2020',
    heardFrom: 'Organic Search'
  },
  {
    id: '9',
    name: 'Ashley Ebert',
    contact: '1-668-550-****',
    altPhone: '415-555-0199',
    email: 'aebert@designstudio.com',
    status: 'follow-up',
    qualification: 'PhD',
    interest: 'UI/UX Design',
    source: 'Social Media',
    assignedTo: 'Jane Smith',
    createdAt: '2025-05-17',
    jobInterest: 'User Research',
    state: 'CA',
    city: 'San Diego',
    passoutYear: '2021',
    heardFrom: 'Dribbble'
  },
  {
    id: '10',
    name: 'Marcus O\'Reilly',
    contact: '1-888-555-0199 x1234',
    altPhone: '617-555-0167',
    email: 'moreilly@cloud.io',
    status: 'qualified',
    qualification: 'Bachelors',
    interest: 'Cloud Solutions',
    source: 'Referral',
    assignedTo: 'John Doe',
    createdAt: '2025-05-16',
    jobInterest: 'AWS Solutions',
    state: 'MA',
    city: 'Boston',
    passoutYear: '2018',
    heardFrom: 'Colleague'
  },
  {
    id: '11',
    name: 'Dr. Samantha Wu',
    contact: '(415) 555-0175 x789',
    altPhone: '650-555-0188',
    email: 'swu@airesearch.edu',
    status: 'converted',
    qualification: 'PhD',
    interest: 'AI Development',
    source: 'Website',
    assignedTo: 'Emily Davis',
    createdAt: '2025-05-15',
    jobInterest: 'Natural Language Processing',
    state: 'CA',
    city: 'Palo Alto',
    passoutYear: '2015',
    heardFrom: 'Research Paper'
  },
  {
    id: '12',
    name: 'Liam Nguyen',
    contact: '213-555-0163 x456',
    altPhone: '310-555-0195',
    email: 'lnguyen@startup.tech',
    status: 'new',
    qualification: 'Masters',
    interest: 'Mobile Apps',
    source: 'Cold Call',
    assignedTo: 'Robert Johnson',
    createdAt: '2025-05-14',
    jobInterest: 'React Native Development',
    state: 'CA',
    city: 'Santa Monica',
    passoutYear: '2023',
    heardFrom: 'Industry Event'
  },
  {
    id: '13',
    name: 'Olivia Kensington',
    contact: '1-800-555-0188 x332',
    altPhone: '212-555-0177',
    email: 'okensington@marketing.pro',
    status: 'follow-up',
    qualification: 'Bachelors',
    interest: 'Digital Marketing',
    source: 'Email Campaign',
    assignedTo: 'John Doe',
    createdAt: '2025-05-13',
    jobInterest: 'Content Strategy',
    state: 'NY',
    city: 'Brooklyn',
    passoutYear: '2020',
    heardFrom: 'Newsletter'
  },
  {
    id: '14',
    name: 'Ethan Blockchain',
    contact: '(650) 555-0169 x888',
    altPhone: '415-555-0190',
    email: 'eblock@crypto.dev',
    status: 'converted',
    qualification: 'Other',
    interest: 'Web3 Development',
    source: 'Social Media',
    assignedTo: 'Jane Smith',
    createdAt: '2025-05-12',
    jobInterest: 'Smart Contracts',
    state: 'CA',
    city: 'San Francisco',
    passoutYear: '2022',
    heardFrom: 'Discord'
  },
  {
    id: '15',
    name: 'Zara Vakili',
    contact: '+1-202-555-0193',
    altPhone: '202-555-0166',
    email: 'zvakili@diplomats.org',
    status: 'qualified',
    qualification: 'PhD',
    interest: 'International Relations',
    source: 'Referral',
    assignedTo: 'Emily Davis',
    createdAt: '2025-05-11',
    jobInterest: 'Policy Analysis',
    state: 'DC',
    city: 'Washington',
    passoutYear: '2017',
    heardFrom: 'Conference'
  }
];